const fs = require('fs');
const path = require('path');

const {
  createRunOncePlugin,
  withAppBuildGradle,
  withDangerousMod,
} = require('expo/config-plugins');

const packageJson = require('../modules/cumquat-native/package.json');

const GRADLE_MARKER = '// @generated by withCumquatNative';
const CMAKE_MARKER = '# @generated by withCumquatNative';

function patchAppBuildGradle(source) {
  if (source.includes(GRADLE_MARKER)) {
    return source;
  }

  const androidBlock = /android\s*\{/;
  if (!androidBlock.test(source)) {
    throw new Error('withCumquatNative could not find the android block in app/build.gradle');
  }

  return source.replace(
    androidBlock,
    (match) => `${match}\n    ${GRADLE_MARKER}\n    externalNativeBuild {\n        cmake {\n            path file("src/main/jni/CMakeLists.txt")\n        }\n    }`,
  );
}

function insertInclude(source) {
  if (source.includes('#include <NativeCumquatModule.h>')) {
    return source;
  }

  const preferredAnchor = '#include <rncore.h>';
  if (source.includes(preferredAnchor)) {
    return source.replace(
      preferredAnchor,
      `${preferredAnchor}\n#include <NativeCumquatModule.h>`,
    );
  }

  const includes = [...source.matchAll(/^#include .+$/gm)];
  if (includes.length === 0) {
    throw new Error('withCumquatNative could not find an include anchor in OnLoad.cpp');
  }

  const last = includes[includes.length - 1];
  const end = last.index + last[0].length;
  return `${source.slice(0, end)}\n#include <NativeCumquatModule.h>${source.slice(end)}`;
}

function insertProvider(source) {
  if (source.includes('name == NativeCumquatModule::kModuleName')) {
    return source;
  }

  const fallback = 'return autolinking_cxxModuleProvider(name, jsInvoker);';
  if (!source.includes(fallback)) {
    throw new Error('withCumquatNative could not find the C++ module provider in OnLoad.cpp');
  }

  return source.replace(
    fallback,
    `if (name == NativeCumquatModule::kModuleName) {\n    return std::make_shared<NativeCumquatModule>(jsInvoker);\n  }\n\n  ${fallback}`,
  );
}

function makeCMake(projectRoot, jniDirectory) {
  const cppDirectory = path.join(
    projectRoot,
    'modules',
    'cumquat-native',
    'cpp',
  );
  const relativeCppDirectory = path
    .relative(jniDirectory, cppDirectory)
    .split(path.sep)
    .join('/');

  return `${CMAKE_MARKER}\ncmake_minimum_required(VERSION 3.22)\nproject(appmodules LANGUAGES CXX)\n\ninclude(\${REACT_ANDROID_DIR}/cmake-utils/ReactNative-application.cmake)\n\nset(CUMQUAT_CPP_DIR "\${CMAKE_CURRENT_LIST_DIR}/${relativeCppDirectory}")\n\ntarget_sources(\${CMAKE_PROJECT_NAME} PRIVATE\n  "\${CUMQUAT_CPP_DIR}/bridge/NativeCumquatModule.cpp"\n  "\${CUMQUAT_CPP_DIR}/core/Engine.cpp"\n  "\${CUMQUAT_CPP_DIR}/geo/Geodesy.cpp"\n  "\${CUMQUAT_CPP_DIR}/projection/Projection.cpp"\n)\n\ntarget_include_directories(\${CMAKE_PROJECT_NAME} PUBLIC\n  "\${CUMQUAT_CPP_DIR}"\n  "\${CUMQUAT_CPP_DIR}/bridge"\n)\n\ntarget_compile_features(\${CMAKE_PROJECT_NAME} PRIVATE cxx_std_20)\n`;
}

function withCumquatNative(config) {
  config = withAppBuildGradle(config, (gradleConfig) => {
    if (gradleConfig.modResults.language !== 'groovy') {
      throw new Error('withCumquatNative currently supports Groovy app/build.gradle files');
    }

    gradleConfig.modResults.contents = patchAppBuildGradle(
      gradleConfig.modResults.contents,
    );
    return gradleConfig;
  });

  config = withDangerousMod(config, [
    'android',
    async (androidConfig) => {
      const projectRoot = androidConfig.modRequest.projectRoot;
      const androidRoot = androidConfig.modRequest.platformProjectRoot;
      const jniDirectory = path.join(
        androidRoot,
        'app',
        'src',
        'main',
        'jni',
      );
      const reactNativeOnLoad = path.join(
        projectRoot,
        'node_modules',
        'react-native',
        'ReactAndroid',
        'cmake-utils',
        'default-app-setup',
        'OnLoad.cpp',
      );

      if (!fs.existsSync(reactNativeOnLoad)) {
        throw new Error(
          `withCumquatNative could not find React Native OnLoad.cpp at ${reactNativeOnLoad}`,
        );
      }

      fs.mkdirSync(jniDirectory, {recursive: true});

      const defaultOnLoad = fs.readFileSync(reactNativeOnLoad, 'utf8');
      const patchedOnLoad = insertProvider(insertInclude(defaultOnLoad));

      fs.writeFileSync(
        path.join(jniDirectory, 'OnLoad.cpp'),
        patchedOnLoad,
        'utf8',
      );
      fs.writeFileSync(
        path.join(jniDirectory, 'CMakeLists.txt'),
        makeCMake(projectRoot, jniDirectory),
        'utf8',
      );

      return androidConfig;
    },
  ]);

  return config;
}

module.exports = createRunOncePlugin(
  withCumquatNative,
  packageJson.name,
  packageJson.version,
);
