// An SVG Radar Mini-Map overlay adds significant contextual awareness to your augmented reality interface. By pulling data from your existing processedMarkers worklet on the native UI thread, you can render a real-time top-down compass radar in the corner of your screen at 60+ FPS without adding extra computational overhead.Because the math runs on the same shared reference object, markers will instantly pop in or out of the mini-map as your custom fingers adjust the minDistance and maxDistance thresholds.Step 1: Mathematical Foundations for Top-Down ProjectionsTo display elements on a flat, circular radar, you must transform your 3D Earth-Centered, Earth-Fixed (ECEF) and Earth-North-Up (ENU) spaces into a local relative 2D coordinate space.
// Instead of projecting points using camera focal grids (Z forward), the radar uses a traditional polar grid mapping system where:The Center Point \((x_c, y_c)\): Represents the user's exact geographical position.The Y-Axis (Up): Points to True North (N).The X-Axis (Right): Points to True East (E).To handle device rotation smoothly, the map calculates the user's horizontal orientation angle (heading) directly from the sensor quaternion data.\(\theta =\text{atan2}\left(2(q_{w}q_{z}+q_{x}q_{y}),1-2(q_{y}^{2}+q_{z}^{2})\right)\)Points are then rotated around the radar center by angle θ so that the top of the mini-map always matches the direction the user's phone is facing.
// Step 2: Implement the Radar UI ComponentThis isolated presentation component reads from your existing processedMarkers shared reference value. It uses a variable max radius window based on your gesture data to dynamically scale markers onto the visual radar boundaries.
import React from 'react';
import { StyleSheet, View } from 'react-native';
import Svg, { Circle, Line } from 'react-native-svg';
import Animated, { useAnimatedProps } from 'react-native-reanimated';

// Wrap native elements for thread handling
const AnimatedCircle = Animated.createAnimatedComponent(Circle);
const AnimatedLine = Animated.createAnimatedComponent(Line);

const RADAR_SIZE = 140; // Total diameter of the radar UI circle widget
const RADAR_RADIUS = RADAR_SIZE / 2;

export function ARRadarOverlay({ streamRef, maxDistanceRef }) {
  
  // Outer enclosure configuration
  return (
    <View style={styles.radarContainer}>
      <Svg width={RADAR_SIZE} height={RADAR_SIZE}>
        {/* Background Grid Rings */}
        <Circle cx={RADAR_RADIUS} cy={RADAR_RADIUS} r={RADAR_RADIUS} fill="rgba(20, 20, 25, 0.75)" stroke="#00ffff" strokeWidth={1.5} />
        <Circle cx={RADAR_RADIUS} cy={RADAR_RADIUS} r={RADAR_RADIUS * 0.66} fill="none" stroke="rgba(0, 255, 255, 0.25)" strokeWidth={1} strokeDasharray="4,4" />
        <Circle cx={RADAR_RADIUS} cy={RADAR_RADIUS} r={RADAR_RADIUS * 0.33} fill="none" stroke="rgba(0, 255, 255, 0.25)" strokeWidth={1} strokeDasharray="4,4" />
        
        {/* Static Directional Crosshair Guideline Markers */}
        <Line x1={RADAR_RADIUS} y1={0} x2={RADAR_RADIUS} y2={RADAR_SIZE} stroke="rgba(0, 255, 255, 0.15)" strokeWidth={1} />
        <Line x1={0} y1={RADAR_RADIUS} x2={RADAR_SIZE} y2={RADAR_RADIUS} stroke="rgba(0, 255, 255, 0.15)" strokeWidth={1} />
        
        {/* Dynamic Target Node Blips Loop */}
        {streamRef.value.map((_, index) => (
          <RadarBlipItem 
            key={`blip-${index}`} 
            index={index} 
            streamRef={streamRef} 
            maxDistanceRef={maxDistanceRef} 
          />
        ))}

        {/* Center Indicator Representing User Position */}
        <Circle cx={RADAR_RADIUS} cy={RADAR_RADIUS} r={4} fill="#ffffff" stroke="#000000" strokeWidth={1} />
      </Svg>
    </View>
  );
}

function RadarBlipItem({ index, streamRef, maxDistanceRef }) {
  
  const animatedBlipProps = useAnimatedProps(() => {
    const node = streamRef.value[index];
    const maxRange = maxDistanceRef.value;

    // Default hidden fallback properties
    if (!node || node.opacity === 0 || maxRange <= 0) {
      return { cx: RADAR_RADIUS, cy: RADAR_RADIUS, opacity: 0 };
    }

    // Read raw relative ground coordinates generated by our main useDerivedValue engine
    const e = node.rawE;
    const n = node.rawN;

    // Use current maximum visibility limit to dynamically scale markers onto the radar radius
    const linearScale = (RADAR_RADIUS - 6) / maxRange; 
    
    // Map spatial coordinates onto the screen grid coordinate system
    let blipX = RADAR_RADIUS + e * linearScale;
    let blipY = RADAR_RADIUS - n * linearScale; // Invert axis direction to match standard layout spaces

    // If an object falls outside the radar boundary, clamp it to the outer rim
    const dx = blipX - RADAR_RADIUS;
    const dy = blipY - RADAR_RADIUS;
    const currentDistancePixels = Math.sqrt(dx * dx + dy * dy);
    const maxAllowedRadius = RADAR_RADIUS - 6;

    if (currentDistancePixels > maxAllowedRadius) {
      const angle = Math.atan2(dy, dx);
      blipX = RADAR_RADIUS + Math.cos(angle) * maxAllowedRadius;
      blipY = RADAR_RADIUS + Math.sin(angle) * maxAllowedRadius;
    }

    return {
      cx: blipX,
      cy: blipY,
      opacity: node.isWithinDistanceWindow ? 0.9 : 0 // Keep visible on radar if it passes distance check but is behind camera
    };
  });

  return (
    <AnimatedCircle 
      r={3.5} 
      fill="#ff00ff" 
      stroke="#ffffff" 
      strokeWidth={0.75} 
      animatedProps={animatedBlipProps} 
    />
  );
}

const styles = StyleSheet.create({
  radarContainer: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: RADAR_SIZE,
    height: RADAR_SIZE,
    borderRadius: RADAR_RADIUS,
    overflow: 'hidden',
    zIndex: 100,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
  }
});

// 6. Step 3: Update the Main Component Engine LoopTo feed data smoothly into the radar layout matrix, update your central useDerivedValue hook inside Quat.jsx to output the raw, unrotated East (rawE) and North (rawN) coordinates alongside your viewport data.
/* ...// ... Inside your core Quat tracking loop wrapper structure ...
const processedMarkers = useDerivedValue(() => {
  const uLat = userLat.value;
  const uLng = userLng.value;
  const uAlt = userAlt.value;
  const currentQuat = quatShared.value;

  const userEcef = workletGeodeticToEcef(uLat, uLng, uAlt);
  const φ = workletToRad(uLat);
  const λ = workletToRad(uLng);

  const fovRad = workletToRad(AR_CONSTANTS.FOV.DEFAULT);
  const focalLengthX = SCREEN_WIDTH / (2 * Math.tan(fovRad / 2));
  const focalLengthY = SCREEN_HEIGHT / (2 * Math.tan(fovRad / 2));

  return ISLANDS.map((island) => {
    const islandEcef = workletGeodeticToEcef(island.lat, island.lng, island.alt);
    
    const dx = islandEcef.x - userEcef.x;
    const dy = islandEcef.y - userEcef.y;
    const dz = islandEcef.z - userEcef.z;

    const e = -Math.sin(λ) * dx + Math.cos(λ) * dy;
    const n = -Math.sin(φ) * Math.cos(λ) * dx - Math.sin(φ) * Math.sin(λ) * dy + Math.cos(φ) * dz;
    const u = Math.cos(φ) * Math.cos(λ) * dx + Math.cos(φ) * Math.sin(λ) * dy + Math.sin(φ) * dz;

    const rawDistance = Math.sqrt(e * e + n * n + u * u);
    const isInDistanceWindow = rawDistance >= minDistance.value && rawDistance <= maxDistance.value;

    // Apply device rotation to the layout matrix vector
    const enuVector = { x: e, y: n, z: u };
    const rotated = workletRotateVector(enuVector, currentQuat);

    const camX = rotated.x;
    const camY = rotated.z; 
    const camZ = rotated.y; 

    let screenX = -9999;
    let screenY = -9999;
    let isFacingCamera = camZ > 0.1;

    if (isFacingCamera) {
      screenX = SCREEN_WIDTH / 2 + (camX * focalLengthX) / camZ;
      screenY = SCREEN_HEIGHT / 2 - (camY * focalLengthY) / camZ;
    }

    const isWithinScreenBounds = screenX >= 0 && screenX <= SCREEN_WIDTH && screenY >= 0 && screenY <= SCREEN_HEIGHT;
    const fullyVisible = isInDistanceWindow && isFacingCamera && isWithinScreenBounds;

    return {
      id: island.id,
      name: island.name,
      x: screenX,
      y: screenY,
      distance: rawDistance,
      opacity: fullyVisible ? 1 : 0,
      
      // EXPORTED EXTENSIONS: Pass raw tracking parameters directly to the radar component
      rawE: e,
      rawN: n,
      isInDistanceWindow: isInDistanceWindow
    };
  });
}, [quatShared, userLat, userLng, userAlt, minDistance, maxDistance]);

7. Step 4: Inject into the Root JSX Layout StructureRender the radar view overlay at the root level of your UI stack view container so it floats above the native camera layer:
return (
  <GestureHandlerRootView style={styles.container}>
    <GestureDetector gesture={panGesture}>
      <View style={styles.container}>
        <CameraView style={StyleSheet.absoluteFillObject} />
        
//         <ARRadarOverlay streamRef={processedMarkers} maxDistanceRef={maxDistance} />
        
//         // Dynamic 3D Floating Spatial Pointer Node Layer
//         <Svg style={StyleSheet.absoluteFillObject}>
//           {ISLANDS.map((island, idx) => (
//             <ARNodePointer key={island.id} index={idx} streamRef={processedMarkers} />
//           ))}
//         </Svg>
//       </View>
//     </GestureDetector>
//   </GestureHandlerRootView>
// );

// Why this design maximizes tracking performanceSingle Iteration Processing: 
// It reuses calculations from the existing ISLANDS.map loop, meaning adding 
// the radar overlay introduces zero extra worklet steps.Smart Off-Screen 
// Tracking: Points located behind the user (isFacingCamera === false) fadeout 
// from the main screen view but remain visible as trackable blips on the mini-map
*/
